[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.18'

evm_version = 'shanghai'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config